### ISSUE TITLE
请问作者可以支持监控抖音作者最新作品url,直接把url写入log吗

### ISSUE THREAD

**Issue by 9ihbd2DZSMjtsf7vecXjz** [Bla1n/WBDmonitor#1]
感谢作者提供这么简洁的工具, 请问作者可以支持监控抖音作者最新作品url,直接把url写入log吗

**Comment by Bla1n** [comment]
我记得未登录状态下也是会返回视频url的，自己改一下正则就好了，暂不支持订制哈（我懒）
